### DISCUSSION TITLE
Talos support

### DISCUSSION THREAD

**Discussion by rothgar** [aquasecurity/kube-bench#1882] [Development]
I was recently running kube-bench on a cluster with [talos linux](https://talos.dev) and there were a few things I had to change in the job spec to make it work. Would you be open to a PR that supports running kube-bench on clusters running on Talos?

Here's a short list of things I had to change:
1. Run in kube-system namespace. Talos has default pod security policies that don't let privileged pods run outside of kube-system. So we either need to create a namespace and annotate it to run privileged pods or run in kube-system.
2. Remove mounts for folders that don't exist. The talos filesystem is read-only and many of the folders that the job tries to mount don't exist on the host. Kubernetes by default tries to create these folders which fails. Folders include anything with `systemd` in the name (talos doesn't use systemd).

I saw there were other job-*.yaml files in the root of the repo and could contribute my working job-talos.yaml file if there would be interest. I'm not sure if a `--benchmark` flag is required for tests against Talos because I haven't figured out all of the test requirements so far.

**Comment by simar7** [comment]
cc @itaysk

**Comment by davralin** [comment]
@rothgar did you keep the job-file somewhere?

**Reply by rothgar** [reply]
Sorry, I didn't.

**Reply by DRuggeri** [reply]
@davralin  - stumbled here looking for rules for Talos and noticed your question. Here's a daemonset that did the job for me.

This dumps to a file on the host which can be retrieved later by `talosctl`, but you can tweak it to suit your preferred approach.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-bench
  namespace: kube-system
  labels:
    app: kube-bench
spec:
  selector:
    matchLabels:
      app: kube-bench
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-bench
    spec:
      hostPID: true

      tolerations:
        - operator: Exists

      containers:
        - name: kube-bench
          image: aquasecurity/kube-bench:v0.15.0

          # Run once, write stable JSON to host, then sleep to avoid DS restart loops
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -euo pipefail

              OUTDIR="/host-results"
              OUTFILE="${OUTDIR}/kube-bench_${NODE_NAME}.json"
              TMPFILE="${OUTFILE}.tmp"

              kube-bench --json --outputfile "${TMPFILE}"
              mv -f "${TMPFILE}" "${OUTFILE}"

              sleep infinity

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          securityContext:
            privileged: true

          volumeMounts:
            # Talos-safe mounts (trimmed vs community job.yaml):
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true

            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true

            - name: usr-bin
              mountPath: /usr/local/mount-from-host/bin
              readOnly: true

            # Host output directory for JSON artifacts
            - name: kube-bench-results
              mountPath: /host-results
              readOnly: false

      # DaemonSet requires Always
      restartPolicy: Always

      volumes:
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes

        - name: var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet

        - name: usr-bin
          hostPath:
            path: /usr/bin

        - name: kube-bench-results
          hostPath:
            path: /var/log/kube-bench
            type: DirectoryOrCreate
```
