### ISSUE TITLE
The `run` command does not appear to honor the `--exit-code` flag

### ISSUE THREAD

**Issue by andrewmyhre** [aquasecurity/kube-bench#1000]
**Overview**

The `--exit-code` command, proposed [here](https://github.com/aquasecurity/kube-bench/discussions/566) and implemented [here](https://github.com/aquasecurity/kube-bench/pull/734), seems to _only_ be honored by the `root` command. It seems to be ignored by the `run` command. 

**How did you run kube-bench?**

In a Kubernetes job with the arguments:

```
          image: aquasec/kube-bench:v0.6.4
          command: ["/usr/local/bin/kube-bench"]
          args:
          - "run"
          - "--benchmark=cis-1.6"
          - "--exit-code=1"
```

**What happened?**

Even though a control is failing, the exit code from the pod is still `0`.

**What did you expect to happen:**

I expected the exit code from the pod to be `1` as I specified in the kube-bench arguments.

**Environment** 

kube-bench version: v0.6.4

Kubernetes version: v0.17.3

**Running processes**

I'm fairly sure the problem is that `exitCodeSelection()` is invoked from `root.go` and nowhere else.
