### ISSUE TITLE
Unable to install kubebench on GKE

### ISSUE THREAD

**Issue by ajinkya1986** [aquasecurity/kube-bench#1346]
**Overview**

We are trying to install kube-bench on GKE. But we are getting read only file system error for `/srv/kubernetes` and `/opt/cni` volume mount directories. So instead of using the directory we are using `emptyDir`. How and what will be the effect if we use `emptyDir`

We ran kubebench with our custom helm chart

After installing the helm chart one of our cron jobs failed due to read only file system error. Following is the error.
`(combined from similar events): Error: failed to generate container "25441f585d69c59f163d51ddf295dd257e27392e79b3f2729" spec: failed to generate spec: failed to mkdir "/srv/kubernetes": mkdir /srv/kubernetes: read-only file system`

**Comment by vaboston** [comment]
Hello, you can add this to run on GKE :
```
             volumeMounts:
            - name: srv-kubernetes
              mountPath: /tmp/kubernetes/
              readOnly: true
 [...]
        volumes:
        - name: srv-kubernetes
          hostPath:
            path: "/tmp/kubernetes"
```
