### ISSUE TITLE
Seems like skip is ignoring the first parameter in the list

### ISSUE THREAD

**Issue by georgekaz** [aquasecurity/kube-bench#1462]
**Overview**
When running the scan with skip parameter, the first is ignored.

e.g. `--skip="1.1.7,1.1.8,1.1.11,1.1.12,1.1.13,1.1.14,1.2.5"` returns 

```
[FAIL] 1.1.7 Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
[INFO] 1.1.8 Ensure that the etcd pod specification file ownership is set to root:root (Automated)
...
```

but ``--skip="0.0,1.1.7,1.1.8,1.1.11,1.1.12,1.1.13,1.1.14,1.2.5"`` returns

```
[INFO] 1.1.7 Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
[INFO] 1.1.8 Ensure that the etcd pod specification file ownership is set to root:root (Automated)
```

**How did you run kube-bench?**

A pod in a cluster based on a cronjob
`kubectl create job --from=cronjob/kube-bench-masters kube-bench-masters-$(date +%s)`

**What happened?**

It ran fine but the results didn't skip all the items as expected

**What did you expect to happen:**

For 1.1.7 to show [INFO] rather than [FAIL]

**Environment** 
It would have been [v0.6.15](https://hub.docker.com/layers/aquasec/kube-bench/v0.6.15/images/sha256-9731fd9825d1c8fe9d82202e837c391d266bd3a600dfe0ebadb8c7cb4430d5f9?context=explore)
```
image: 'aquasec/kube-bench:latest'
imagePullPolicy: Always
```

k8s 1.26.5

**Running processes**

Not relevant to the issue

**Configuration files**

a snippet from the manifest

```
    - args:
        - '--skip="1.1.7,1.1.8,1.1.11,1.1.12,1.1.13,1.1.14,1.2.5"'
      command:
        - kube-bench
        - run
        - '--targets'
        - master
      image: 'aquasec/kube-bench:latest'
      imagePullPolicy: Always
 ```

I worked around it by adding a another entry of 0.0 as the first entry as can be seen in Overview
