### ISSUE TITLE
Flags set vs. default values

### ISSUE THREAD

**Issue by jnummelin** [aquasecurity/kube-bench#204]
I guess this is more of a question or starter for a discussion. :)

I've hit into one specific case:
```
1.1.23 Ensure that the --service-account-lookup argument is set to true (Scored)
```

Looking up the documentation on it at https://v1-11.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
> --service-account-lookup     Default: true
>     If true, validate ServiceAccount tokens exist in etcd as part of authentication.

The test for it clearly verifies that the option is set to `true`:
```
- id: 1.1.23
    text: "Ensure that the --service-account-lookup argument is set to true (Scored)"
    audit: "ps -ef | grep $apiserverbin | grep -v grep"
    tests:
      test_items:
      - flag: "--service-account-lookup"
        compare:
          op: eq
          value: true
        set: true
```

So in this case, and there's few more cases like this, it's kinda false-positive IMO as the option defaults to true. Wouldn't it be better to write the test as checking that the option is not `false`, maybe something like this:
```
- id: 1.1.23
    text: "Ensure that the --service-account-lookup argument is set to true (Scored)"
    audit: "ps -ef | grep $apiserverbin | grep -v grep"
    tests:
      test_items:
      - flag: "--service-account-lookup"
        compare:
          op: neq # Dunno if there's neq operator in the framework :)
          value: false
```

So to make kube-bench quiet, we have to set many of the flags "unnecessarily" even though they do default to sensible values.

If there's been this sort of discussion already before and I was too blind to find it, please close this one. :) (and maybe point me to the previous results)
