### ISSUE TITLE
Flag root:root does not work with PSP

### ISSUE THREAD

**Issue by pipo02mix** [aquasecurity/kube-bench#213]
I have run kube bench against my cluster but I detected the rules which check the ownership of the configuration files fail because of unexpected output from command.

For example, for the API server config file it executes
```
"/bin/sh -c 'if test -e $apiserverconf; then stat -c %U:%G $apiserverconf; fi'"
```
And the result is `root:UNKNOWN` (instead of `root:root`)

I guess it can related to my set up. The cluster has PSP active and by default it assigns a `restrictive` policy. I have given it privileges but it still showing same value. The current PSP looks like
```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65536
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
```
The cluster has version `1.12.3` of Kubernetes and the OS in the machine is CoreOS (1967.4.0)

Any ideas why the command does not show correct group value?
Run it on the machine directly works

**Comment by lizrice** [comment]
Sounds like the process running the command can't access the /etc/group file and therefore can't determine the group's name. 

How are you running kube-bench - directly on the node with `./kube-bench`, in a container with `docker run`, or in a pod? Are you mounting any directories?

**Comment by lizrice** [comment]
Also @pipo02mix please could you clarify, does this work as expected for you if there is no PSP, and only fails if the PSP is in place?

**Comment by pipo02mix** [comment]
> How are you running kube-bench - directly on the node with ./kube-bench, in a container with docker run, or in a pod? Are you mounting any directories?

In a pod and I mount these volumes
```
volumes:
      - name: var-lib-kubelet
        hostPath:
          path: "/var/lib/kubelet"
      - name: etc-systemd
        hostPath:
          path: "/etc/systemd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: srv-kubernetes
        hostPath:
          path: "/srv"
```
