### ISSUE TITLE
Add ":" as a valid flag-value separator for tests

### ISSUE THREAD

**Issue by ttousai** [aquasecurity/kube-bench#241]
## Problem
Kube-bench does not support extracting the value for flags in the form 'flag: value'. This makes writing tests for such flags complex and limits which comparison operators are available.

For example to correctly check that the value of 'read-only-port' is set to '0' in the output of an audit command that returns the output 'read-only-port: 0', the following tests must be used in the current version of kube-bench:

```
...
- flag: "read-only-port: 0"
    compare:
      op: has
      value: "0"  
```
or
```
...
- flag: "read-only-port: 0"
  set: true
```
It is not clear that we are checking that the value of 'read-only-port' is '0'. We also can't use the 'gt(e)' and 'lt(e)' operators in these tests.

## Proposed Solution
To support value extraction from flags in the aforementioned form, we must add ':' to the current list of accepted flag-value separators ('=' and  ' ').

When this solution is implemented the above example will be written as:
```
...
- flag: "read-only-port"
    compare:
      op: eq
      value: "0"  
```
In this test it is obvious we are checking the flag 'read-only-port' is set to 0. We can also use other operators like 'gt(e)' and 'lt(e)' which we couldn't use in the previous tests.
