### ISSUE TITLE
How to run kube bench on multiple master and worker nodes ?

### ISSUE THREAD

**Issue by anjaligau** [aquasecurity/kube-bench#266]
Hi ,
I am able to run job-master.yaml and job-worker.yaml  for master and worker node respectively.

What I want is kube bench should check my all three master and worker nodes  , it should be like if I initiate my kube bench check from my workstation , my all nodes should be checked .

As of now kube bench master and worker yaml file only running  on master2 and worker1.

Regards
Anjali

**Comment by ttousai** [comment]
@anjaligau you will have to create a daemonset for master check and another for node checks. 
Just change `apiVersion` to `apps/v1` and `type` to `DaemonSet` in the job-master.yaml and job-node.yaml files.

For example job-node.yaml:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-bench-node
spec:
  template:
    spec:
      hostPID: true
      containers:
      - name: kube-bench
        image: aquasec/kube-bench:latest
        command: ["kube-bench","node"]
        volumeMounts:
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
        - name: etc-systemd
          mountPath: /etc/systemd
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          # /usr/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version. 
          # You can omit this mount if you specify --version as part of the command.           
        - name: usr-bin
          mountPath: /usr/bin
      restartPolicy: Never
      volumes:
      - name: var-lib-kubelet
        hostPath:
          path: "/var/lib/kubelet"
      - name: etc-systemd
        hostPath:
          path: "/etc/systemd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: usr-bin
        hostPath:
          path: "/usr/bin"
```

kube-bench has a feature to auto-detect node types but it is currently buggy #264.

**Comment by anjaligau** [comment]
hey 

@ttousai thanks but while running I am getting this error , 

"error: error validating "./job.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false"

**Comment by ttousai** [comment]
@anjaligau many apologies, I missed a required field in the daemonset spec, please use this instead for node checks:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-bench-node-ds
spec:
  selector:
    matchLabels:
      name: kube-bench
  template:
    metadata:
      labels:
        name: kube-bench
    spec:
      containers:
      - name: kube-bench
        image: aquasec/kube-bench:latest
        command: ["kube-bench","node"]
        volumeMounts:
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
        - name: etc-systemd
          mountPath: /etc/systemd
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          # /usr/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version. 
          # You can omit this mount if you specify --version as part of the command.           
        - name: usr-bin
          mountPath: /usr/bin
      volumes:
      - name: var-lib-kubelet
        hostPath:
          path: "/var/lib/kubelet"
      - name: etc-systemd
        hostPath:
          path: "/etc/systemd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: usr-bin
        hostPath:
          path: "/usr/bin"
```
and for master checks:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-bench-master-ds
spec:
  selector:
    matchLabels:
      name: kube-bench-master
  template:
    metadata:
      labels:
        name: kube-bench-master
    spec:
      nodeSelector: 
        node-role.kubernetes.io/master: "" 
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostPID: true
      containers:
      - name: kube-bench-master
        image: aquasec/kube-bench:latest
        command: ["kube-bench","master"]
        volumeMounts:
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          # /usr/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version. 
          # You can omit this mount if you specify --version as part of the command.
        - name: usr-bin
          mountPath: /usr/bin
      volumes:
      - name: var-lib-etcd
        hostPath:
          path: "/var/lib/etcd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: usr-bin
        hostPath:
          path: "/usr/bin"
```
