### ISSUE TITLE
Support multiple releases of Kubernetes (including 1.6)

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#41]
Not everyone is running 1.7 yet, and in the future no doubt there will be folks running on 1.7 for some time after 1.8 is released, and so on. We should support running the right set of tests for the version that we detect. 

We could do this with new optional fields for each test in the YAML
* _retired-in: <release number>_ - if this is set, don't load this test if the detected release >= specified release number
* _added-in: <release number>_ - if this is set, don't load this test if the detected release < specified release number

To support kubernetes 1.6 we need to identify the new tests for 1.7 and add _added-in: 1.7_  for them, and also add back any tests we removed, giving them _retired-in: 1.7_

**Comment by lizrice** [comment]
Adding a bit more clarity:

- Detect the release being used on this machine. 
- Read the test file and for each test case: 
  -  If the test case has both _added-in_ and _retired-in_, and if _added-in_ >= _retired-in_, then this test case is illegal and we should throw an error. 
  - If (test case has _added-in_, and _added-in_ > detected release) or (test case has _retired-in_, and _retired-in_ <= detected release) then skip this test case, else run this test case 

We should check the test cases as we read them in from the config file - that way we can drop any possible duplicate IDs. For example if 1.6 had a test 3.4.1, and then in 1.7 it was removed but replaced with a different 3.4.1, then our yaml file would contain something like this:

```
checks:
  ...
  - id: 3.4.1
     retired-in: 1.7
     ...

  - id: 3.4.1
    added-in: 1.7
    ...
```  

This would be legal: we'd run the first of these alternatives if the detected release was 1.6, and we'd run the second if the detected release was 1.7.

**Comment by ttousai** [comment]
I have started merging the tests from CIS Benchmarks 1.0.0 and 1.1.0, and I have noticed this proposal works brilliantly for addition and removal of tests where there is no renumbering or rearranging of tests, that is where the addition or removal happens at the end of the test group.

If the test is added or removed from anywhere apart from the bottom of the test group, there is some amount of duplication and the number of duplication depends on how close to the bottom the change is. Generally, the closer to the top of the test group, the more the duplication for just a single change.

For example:
Assume the following to convert cfg/master.yaml from CIS Kubernetes Benchmark 1.0.0 to 1.1.0:
- current version of cfg/master.yaml = CIS 1.0.0
- desired version of cfg/master.yaml = CIS 1.1.0
- action: remove test 1.3.3 and renumber remaining tests in the 1.3 group.

cfg/master.yaml looks like this:
```yaml
...
    - id: 1.3.3
      text: "Ensure that the --insecure-experimental-approve-all-kubelet-csrs-for-group argument is not set (Scored)"
      audit: "ps -ef | grep $controllermanagerbin | grep -v grep"
      retired-in: 1.7
      tests:
        test_items:
        - flag: "--insecure-experimental-approve-all-kubelet-csrs-for-group"
          set: false
      remediation: "Edit the $controllermanagerconf file on the master node and remove 
              the -insecure-experimental-approve-all-kubelet-csrs-for-group argument from the 
              KUBE_CONTROLLER_MANAGER_ARGS parameter"
      scored: true

    - id: 1.3.4
      text: "Ensure that the --use-service-account-credentials argument is set"
      audit: "ps -ef | grep $controllermanagerbin | grep -v grep"
      retired-in: 1.7
      tests:
        test_items:
        - flag: "--use-service-account-credentials"
          compare:
            op: eq
            value: true
          set: true
      remediation: "Edit the $controllermanagerconf file on the master node and set the 
              KUBE_CONTROLLER_MANAGER_ARGS parameter to --use-service-account-credentials=true"
      scored: true

    - id: 1.3.3
      text: "Ensure that the --use-service-account-credentials argument is set"
      audit: "ps -ef | grep $controllermanagerbin | grep -v grep"
      added-in: 1.7
      tests:
        test_items:
        - flag: "--use-service-account-credentials"
          compare:
            op: eq
            value: true
          set: true
      remediation: "Edit the $controllermanagerconf file on the master node and set the 
              KUBE_CONTROLLER_MANAGER_ARGS parameter to --use-service-account-credentials=true"
      scored: true

    - id: 1.3.5
      text: "Ensure that the --service-account-private-key-file argument is set as appropriate (Scored)"
      audit: "ps -ef | grep $controllermanagerbin | grep -v grep"
      retired-in: 1.7
      tests:
        test_items:
        - flag: "--service-account-private-key-file"
          set: true
      remediation: "Edit the $controllermanagerconf file on the master node and set the 
              KUBE_CONTROLLER_MANAGER_ARGS parameter to --service-account-private-keyfile=<filename>"
      scored: true

    - id: 1.3.4
      text: "Ensure that the --service-account-private-key-file argument is set as appropriate (Scored)"
      audit: "ps -ef | grep $controllermanagerbin | grep -v grep"
      added-in: 1.7
      tests:
        test_items:
        - flag: "--service-account-private-key-file"
          set: true
      remediation: "Edit the $controllermanagerconf file on the master node and set the 
              KUBE_CONTROLLER_MANAGER_ARGS parameter to --service-account-private-keyfile=<filename>"
      scored: true

    - id: 1.3.6
      text: "Ensure that the --root-ca-file argument is set as appropriate (Scored)"
      audit: "ps -ef | grep $controllermanagerbin | grep -v grep"
      retired-in: 1.7
      tests:
        test_items:
        - flag: "--root-ca-file"
          set: true
      remediation: "Edit the $controllermanagerconf file on the master node and set the 
              KUBE_CONTROLLER_MANAGER_ARGS parameter to include --root-ca-file=<file>"
      scored: true

    - id: 1.3.5
      text: "Ensure that the --root-ca-file argument is set as appropriate (Scored)"
      audit: "ps -ef | grep $controllermanagerbin | grep -v grep"
      added-in: 1.7
      tests:
        test_items:
        - flag: "--root-ca-file"
          set: true
      remediation: "Edit the $controllermanagerconf file on the master node and set the 
              KUBE_CONTROLLER_MANAGER_ARGS parameter to include --root-ca-file=<file>"
      scored: true

    - id: 1.3.7
      text: "Apply Security Context to Your Pods and Containers (Not Scored)"
      retired-in: 1.7
      type: "manual"
      remediation: "Edit the /etc/kubernetes/controller-manager file on the master node and set the
              KUBE_CONTROLLER_MANAGER_ARGS parameter to a value to include 
              \"--feature-gates=RotateKubeletServerCertificate=true\""
      scored: false

    - id: 1.3.6
      text: "Apply Security Context to Your Pods and Containers (Not Scored)"
      added-in: 1.7
      type: "manual"
      remediation: "Edit the /etc/kubernetes/controller-manager file on the master node and set the
              KUBE_CONTROLLER_MANAGER_ARGS parameter to a value to include 
              \"--feature-gates=RotateKubeletServerCertificate=true\""
      scored: false

    - id: 1.3.8
      text: " Ensure that the RotateKubeletServerCertificate argument is set to true (Scored)"
      retired-in: 1.7
      audit: "ps -ef | grep $controllermanagerbin | grep -v grep"
      tests:
        test_items:
        - flag: "RotateKubeletServerCertificate"
          compare:
            op: eq
            value: true
          set: true
      remediation: "Edit the /etc/kubernetes/controller-manager file on the master node and set the
              KUBE_CONTROLLER_MANAGER_ARGS parameter to a value to include 
              \"--feature-gates=RotateKubeletServerCertificate=true\""
      scored: true

    - id: 1.3.7
      text: " Ensure that the RotateKubeletServerCertificate argument is set to true (Scored)"
      added-in: 1.7
      audit: "ps -ef | grep $controllermanagerbin | grep -v grep"
      tests:
        test_items:
        - flag: "RotateKubeletServerCertificate"
          compare:
            op: eq
            value: true
          set: true
      remediation: "Edit the /etc/kubernetes/controller-manager file on the master node and set the
              KUBE_CONTROLLER_MANAGER_ARGS parameter to a value to include 
              \"--feature-gates=RotateKubeletServerCertificate=true\""
      scored: true
```

The ripple effect of such a renumbering can be massive, especially if it occurs over multiple versions of the CIS benchmark and we will see the number of checks growing exponentially and most of the growth will be because of duplicates of existing test.

A single removal can have a huge and disproportional effect on the size and number of tests we keep in our test definition files. If for example check 1.1.1 is removed in a future version from the test group 1.1 which has about 32 tests, it will result in us duplicating about 31 tests resulting in approximately 64 tests about 30 of which we will not run.

I don't think this rate of growth is manageable or even useful.

Any thoughts?
