### ISSUE TITLE
Openshift 3.11 Complains About Use of hostPID: true

### ISSUE THREAD

**Issue by robertojrojas** [aquasecurity/kube-bench#519]
When running the provided **job.yaml** against OpenShift 3.11, the job fails to be scheduled. 
The following error is displayed by running **ocp get events** 

```console
8s          18s          2         kube-bench.15d54bc249428dd1   Job                   
Warning   FailedCreate   job-controller   Error creating: pods "kube-bench-" is forbidden: 
unable to validate against any security context constraint: 
[provider restricted: .spec.securityContext.hostPID: Invalid value: true: 
Host PID is not allowed to be used 
spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.containers[0].securityContext.hostPID: Invalid value: true: Host PID is not allowed to be 
used]

```

One way to fix this problem is with the following steps:

- `oc create namespace kube-bench` 

- `oc adm policy add-scc-to-user -n kube-bench privileged -z default`

- create the following file **` job-ocp.yaml`**

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
  namespace: kube-bench
spec:
  template:
    metadata:
      labels:
        app: kube-bench
    spec:
      hostPID: true
      containers:
      - name: kube-bench
        image: aquasecurity/kube-bench:0.2.0
        command: ["kube-bench", "node", "--version", "ocp-3.11"]
        imagePullPolicy: Always
        volumeMounts:
        - name: etc-origin
          mountPath: /etc/origin
      restartPolicy: Never
      volumes:
      - name: etc-origin
        hostPath:
          path: "/etc/origin"
```
