### ISSUE TITLE
[feature]: Support test override files

### ISSUE THREAD

**Issue by micahhausler** [aquasecurity/kube-bench#571]
Thanks for this tool! We at AWS have a change we’d like to suggest and would love community input and participation in implementing this.

The CIS Kubernetes Benchmark is a widely recognized guideline for operating and configuring Kubernetes and its various components, but is opinionated in how configuration is set in ways that not all hosted solutions of Kubernetes might agree with.

The proposal I have is for kube-bench is to have a new “config overlay” feature. Taking the node configuration and command as an example, the code currently loads one YAML config file containing the test criteria (ex: [node.yaml](https://github.com/aquasecurity/kube-bench/blob/037bb147298548ce58f723431befc14982ebf0e3/cfg/cis-1.5/node.yaml)) and loads how certain tests are scored, the remediation description, and other inputs for the test. In order to allow providers to change certain fields for a test (es: switching “scored” to false, providing a different text description), could kube-bench support a second file that could contain test overrides? 

Given the following test file example: (not that there is anything wrong with this specific test)

```yaml
controls:
version: 1.5
id: 4
text: "Worker Node Security Configuration"
type: "node"
groups:
  # ...
  - id: 4.1
    text: "Worker Node Configuration Files"
    checks:
    - id: 4.1.7
      text: "Ensure that the certificate authorities file permissions are set to 644 or more restrictive (Scored)"
      types: "manual"
      remediation: |
        Run the following command to modify the file permissions of the
        --client-ca-file chmod 644 <filename>
      scored: true
```

If a provider wanted to set test 4.1.7 to not be scored, and provide reasoning, they could supply the following override file:

```yaml
controls:
version: 1.5
id: 4
text: "Worker Node Security Configuration"
type: "node"
groups:
  - id: 4.1
    text: "Worker Node Configuration Files"
    checks:
    - id: 4.1.7
      scored: false
```

and a user would call:

```bash
kube-bench node -f node.yaml --override provider.yaml
```

I think changes to the CIS benchmark are outside the scope of this project, and it is worth it for vendors (AWS included) to work toward refining the common benchmark, but this would be a way for providers to easily iterate and provide their own override files.
