### ISSUE TITLE
Unable to detect running programs for component "apiserver"

### ISSUE THREAD

**Issue by ramesh-ramani** [aquasecurity/kube-bench#608]
Installed this as a pod in my cluster and I seem to be getting this error. Not sure why. Can someone help? I've used the same yaml file as the jobs-eks.yaml file. Just a heads-up though, I've applied a PSP to the pod's namespace. The PSP has dropped all capabilities, runs as user 999, alloweprivilegeEscalation: False, has a serviceaccount which has permissions to only use the PSP and nothing else. Does the ServiceAccount need some special permissions?

```
W0416 20:50:20.243561   11207 util.go:108] 
Unable to detect running programs for component "apiserver"
The following "master node" programs have been searched, but none of them have been found:
	- kube-apiserver
	- hyperkube apiserver
	- hyperkube kube-apiserver
	- apiserver


These program names are provided in the config.yaml, section 'master.apiserver.bins'
log: exiting because of error: log: cannot create log: open /tmp/kube-bench.kube-bench-j6hh2.unknownuser.log.WARNING.20200416-205020.11207: read-only file system
```

**Comment by mozillazg** [comment]
`hostPID=true` is needed.

**Comment by ramesh-ramani** [comment]
> `hostPID=true` is needed.

I have included that in the pod spec but that does not seem to help either. Here's the Pod spec:

```
    spec:
      hostPID: true
      nodeSelector:
        workload: normal
      serviceAccountName: kube-bench-sa
      tolerations:
      - key: workload
        operator: Equal
        value: normal
        effect: NoSchedule
      containers:
        - name: kube-bench
          # Push the image to your ECR and then refer to it here
          image: aquasec/kube-bench:0.2.3
          command: ["kube-bench", "--version", "1.11"]
          volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
      securityContext:
         runAsUser: 999
      restartPolicy: Never
      volumes:
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
```
