### ISSUE TITLE
Bin_op "and" doesn't seem to be working

### ISSUE THREAD

**Issue by jasmingacic** [aquasecurity/kube-bench#747]
I ran `kube-bench master` on the master node with specific configuration.

Checks cis-1.6 1.2.5 and  1.2.29 are supposed to be checking that both requested parameters are set:
```
- id: 1.2.5
        text: "Ensure that the --kubelet-client-certificate and --kubelet-client-key arguments are set as appropriate (Automated)"
        audit: "/bin/ps -ef | grep $apiserverbin | grep -v grep"
        tests:
          bin_op: and
          test_items:
            - flag: "--kubelet-client-certificate"
            - flag: "--kubelet-client-key"
```

Even if the output is like this:
```
# ps -ef | grep "var/lib/mke/bin/kube-apiserver" | grep -v grep
root        1332    1315 17 09:37 ?        00:49:00 /var/lib/mke/bin/kube-apiserver --tls-private-key-file=/var/lib/mke/pki/server.key --enable-admission-plugins=NodeRestriction --secure-port=6443 --enable-bootstrap-token-auth=true --advertise-address=147.75.87.81 --proxy-client-cert-file=/var/lib/mke/pki/front-proxy-client.crt --service-account-signing-key-file=/var/lib/mke/pki/sa.key --requestheader-group-headers=X-Remote-Group 
--kubelet-client-key=/var/lib/mke/pki/apiserver-kubelet-client.key 
--authorization-mode=Node,RBAC 
--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --insecure-port=0 --client-ca-file=/var/lib/mke/pki/ca.crt 
--kubelet-client-certificate=/var/lib/mke/pki/apiserver-kubelet-client.crt 
--service-account-key-file=/var/lib/mke/pki/sa.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/var/lib/mke/pki/server.crt --requestheader-allowed-names=front-proxy-client --service-account-issuer=api --api-audiences=system:konnectivity-server --proxy-client-key-file=/var/lib/mke/pki/front-proxy-client.key --requestheader-client-ca-file=/var/lib/mke/pki/front-proxy-ca.crt --egress-selector-config-file=/var/lib/mke/konnectivity.conf --allow-privileged=true --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-username-headers=X-Remote-User --etcd-servers=https://127.0.0.1:2379 --etcd-cafile=/var/lib/mke/pki/etcd/ca.crt --etcd-certfile=/var/lib/mke/pki/apiserver-etcd-client.crt --etcd-keyfile=/var/lib/mke/pki/apiserver-etcd-client.key
```
The check fails:

```
1.2.5 Follow the Kubernetes documentation and set up the TLS connection between the
apiserver and kubelets. Then, edit API server pod specification file
/etc/kubernetes/manifests/kube-apiserver.yaml on the master node and set the
kubelet client certificate and key parameters as below.
--kubelet-client-certificate=<path/to/client-certificate-file>
--kubelet-client-key=<path/to/client-key-file>
```

I ran it in a specific configuration on Ubuntu 20.04

Version **kube-bench_0.3.1_linux_amd64**
