### ISSUE TITLE
Test 'Ensure that the RotateKubeletServerCertificate argument is set to true' fails if there are other feature-gates parameter defined

### ISSUE THREAD

**Issue by arno-snop** [aquasecurity/kube-bench#789]
**What steps did you take and what happened:**

Following test on master (cis 1.6):
```
      - id: 1.3.6
        text: "Ensure that the RotateKubeletServerCertificate argument is set to true (Automated)"
        audit: "/bin/ps -ef | grep $controllermanagerbin | grep -v grep"
        tests:
          test_items:
            - flag: "--feature-gates"
              compare:
                op: eq
                value: "RotateKubeletServerCertificate=true"
        remediation: |
          Edit the Controller Manager pod specification file $controllermanagerconf
          on the master node and set the --feature-gates parameter to include RotateKubeletServerCertificate=true.
          --feature-gates=RotateKubeletServerCertificate=true
        scored: true
```

fails in case there are other feature-gates parameters defined even if `RotateKubeletServerCertificate=true` is set.

**What did you expect to happen:**

Test should succeed even if there are other feature-gates parameters defined.

**Environment** 

kube-bench 0.4.0
CIS 1.6
kubernetes 1.18.9

**Anything else you would like to add:**

I think test should be:
```
                op: has
```

instead of 
```
                op: eq
```

**Comment by yoavrotems** [comment]
Hey, I think you are using an old version, currently in main branch (we are no longer using master) https://github.com/aquasecurity/kube-bench/blob/main/cfg/cis-1.6/master.yaml#L917 
You can see this test is now check its not set to false: 
```
      - id: 1.3.6
        text: "Ensure that the RotateKubeletServerCertificate argument is set to true (Automated)"
        audit: "/bin/ps -ef | grep $controllermanagerbin | grep -v grep"
        tests:
          bin_op: or
          test_items:
            - flag: "--feature-gates"
              compare:
                op: nothave
                value: "RotateKubeletServerCertificate=false"
              set: true
            - flag: "--feature-gates"
              set: false
        remediation: |
          Edit the Controller Manager pod specification file $controllermanagerconf
          on the master node and set the --feature-gates parameter to include RotateKubeletServerCertificate=true.
          --feature-gates=RotateKubeletServerCertificate=true
        scored: true
```

I think this solves your issue, 
if this is still an issue you are welcome to reopen this issue.
