### ISSUE TITLE
Wrong test for experimental-encryption-provider-config on Openshift

### ISSUE THREAD

**Issue by tonyqui** [aquasecurity/kube-bench#926]
**Overview**

Test 1.34 for RH-07 seems to be apparently wrong:

https://github.com/aquasecurity/kube-bench/blob/6605ff884448fdc0a3beb1682098eacb87a7b52c/cfg/rh-0.7/master.yaml#L592

This asserts the following payload:

providers:
  - aescbc:
    experimental-encryption-provider-config:
      aescbc
...

However from Openshift 3.11 configuration page it seems that the configuration looks:
providers:
  - aescbc:
    keys:
    - name:
       secret:

Reference: 
https://docs.openshift.com/container-platform/3.11/admin_guide/encrypting_data.html#encrypting-data-configuration

**How did you run kube-bench?**

Run kube-bench using _benchmark=rh-0.7_

**What happened?**

Test reported as failed

**What did you expect to happen:**

Test should be successful

**Environment** 

Openshift 3.11

**Running processes**

**Configuration files**

**Anything else you would like to add:**

**Comment by tonyqui** [comment]
It would be great if anyone could point to which guideline/reference the test is inspired to.

**Comment by yoavrotems** [comment]
Hey thank you for reporting us, those tests are made from an hardening guide we got from rhel in the time. 
I think the issue is not in the audit_config query but in the `path`
All the audit command does is cat the encryption-config.yaml
```
kubernetesMasterConfig:
  apiServerArguments:
    experimental-encryption-provider-config:
    - /path/to/encryption-config.yaml
```
The `path` command should be change (follows same logic as jq) 
https://github.com/aquasecurity/kube-bench/blob/6605ff884448fdc0a3beb1682098eacb87a7b52c/cfg/rh-0.7/master.yaml#L595-L598
which may needs to be 
```
- path: "{.resources.providers.aescbc}" 
  compare: 
    op: has 
    value: "name" 
```

could you test it in your env?
