### ISSUE TITLE
Unable to target cis-1.20 on k8s cluster 1.20.8

### ISSUE THREAD

**Issue by rajan123456** [aquasecurity/kube-bench#927]
**Overview**

I am trying to use kube-bench for scanning cis-1.20 on my on-prem kubernetes cluster (v1.20.8). However, kube-bench is targetting with cis-1.6 only. If I force specify the target version: cis-1.20, the scan errors out completely.

**How did you run kube-bench?**

I am using the job-master.yml and job-node.yml for running scans on my cluster within k8s.

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench-master
spec:
  template:
    spec:
      hostPID: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      imagePullSecrets:
      - name: my-private-creds
      containers:
        - name: kube-bench
          image: my-private-repo/kube-bench:latest
          command: ["kube-bench", "run", "--targets=master,node,controlplane,etcd,policies"]
          # command: ["kube-bench", "run", "--targets=master,node,controlplane,etcd,policies", "--benchmark", "cis-1.20"]
          volumeMounts:
            - name: var-lib-etcd
              mountPath: /var/lib/etcd
              readOnly: true
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: var-lib-kube-scheduler
              mountPath: /var/lib/kube-scheduler
              readOnly: true
            - name: var-lib-kube-controller-manager
              mountPath: /var/lib/kube-controller-manager
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: lib-systemd
              mountPath: /lib/systemd/
              readOnly: true
            - name: srv-kubernetes
              mountPath: /srv/kubernetes/
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
              # /usr/local/mount-from-host/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version.
              # You can omit this mount if you specify --version as part of the command.
            - name: usr-bin
              mountPath: /usr/local/mount-from-host/bin
              readOnly: true
            - name: etc-cni-netd
              mountPath: /etc/cni/net.d/
              readOnly: true
            - name: opt-cni-bin
              mountPath: /opt/cni/bin/
              readOnly: true
            - name: etc-passwd
              mountPath: /etc/passwd
              readOnly: true
            - name: etc-group
              mountPath: /etc/group
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: var-lib-etcd
          hostPath:
            path: "/var/lib/etcd"
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: var-lib-kube-scheduler
          hostPath:
            path: "/var/lib/kube-scheduler"
        - name: var-lib-kube-controller-manager
          hostPath:
            path: "/var/lib/kube-controller-manager"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: lib-systemd
          hostPath:
            path: "/lib/systemd"
        - name: srv-kubernetes
          hostPath:
            path: "/srv/kubernetes"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
        - name: usr-bin
          hostPath:
            path: "/usr/bin"
        - name: etc-cni-netd
          hostPath:
            path: "/etc/cni/net.d/"
        - name: opt-cni-bin
          hostPath:
            path: "/opt/cni/bin/"
        - name: etc-passwd
          hostPath:
            path: "/etc/passwd"
        - name: etc-group
          hostPath:
            path: "/etc/group"
```

**What happened?**

Logs: (V3) (No Benchmark Specified)

I0706 01:38:33.839426   24583 util.go:286] Kubernetes REST API Reported version: &{1 20  v1.20.8}
I0706 01:38:33.839456   24583 common.go:282] mapToBenchmarkVersion for k8sVersion: "1.20" cisVersion: "" found: false
I0706 01:38:33.839466   24583 common.go:286] mapToBenchmarkVersion for k8sVersion: "1.19" cisVersion: "cis-1.6" found: true
I0706 01:38:33.839475   24583 common.go:348] Mapped Kubernetes version: 1.20 to Benchmark version: cis-1.6
I0706 01:38:33.839484   24583 common.go:351] Kubernetes version: "1.20" to Benchmark version: "cis-1.6"
I0706 01:38:33.839493   24583 run.go:40] Checking targets [node controlplane etcd policies] for cis-1.6 

Logs: (--benchmark cis-1.20)
error validating targets: No targets configured for cis-1.20

**What did you expect to happen:**

- kube-bench should automatically pick cis-1.20 for target cluster k8s v1.20.8
- kube-bench should not error out if --benchmark=cis-1.20 is specified

**Environment** 

Using this docker image: aquasec/kube-bench:latest
Unable to get any output if I run the job with 
```
command: ["kube-bench", "version", "-v", "3"]
``` 

Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}

**Running processes**
Redacted, will share if needed.

**Configuration files**
Shared the job definition already.

**Anything else you would like to add:**
NA
