### ISSUE TITLE
[FAIL] 4.2.6 on node

### ISSUE THREAD

**Issue by brainfair** [aquasecurity/kube-bench#948]
**Overview**

After scan 
[FAIL] 4.2.6 Ensure that the --protect-kernel-defaults argument is set to true (Automated)

But in /etc/kubernetes/kubelet-config.yaml
protectKernelDefaults: true

**How did you run kube-bench?**

DaemonSet

**What happened?**

```[INFO] 4 Worker Node Security Configuration
[INFO] 4.1 Worker Node Configuration Files
[PASS] 4.1.1 Ensure that the kubelet service file permissions are set to 644 or more restrictive (Automated)
[PASS] 4.1.2 Ensure that the kubelet service file ownership is set to root:root (Automated)
[PASS] 4.1.3 If proxy kubeconfig file exists ensure permissions are set to 644 or more restrictive (Manual)
[PASS] 4.1.4 Ensure that the proxy kubeconfig file ownership is set to root:root (Manual)
[PASS] 4.1.5 Ensure that the --kubeconfig kubelet.conf file permissions are set to 644 or more restrictive (Automated)
[PASS] 4.1.6 Ensure that the --kubeconfig kubelet.conf file ownership is set to root:root (Manual)
[PASS] 4.1.7 Ensure that the certificate authorities file permissions are set to 644 or more restrictive (Manual)
[PASS] 4.1.8 Ensure that the client certificate authorities file ownership is set to root:root (Manual)
[PASS] 4.1.9 Ensure that the kubelet --config configuration file has permissions set to 644 or more restrictive (Automated)
[PASS] 4.1.10 Ensure that the kubelet --config configuration file ownership is set to root:root (Automated)
[INFO] 4.2 Kubelet
[PASS] 4.2.1 Ensure that the anonymous-auth argument is set to false (Automated)
[PASS] 4.2.2 Ensure that the --authorization-mode argument is not set to AlwaysAllow (Automated)
[PASS] 4.2.3 Ensure that the --client-ca-file argument is set as appropriate (Automated)
[PASS] 4.2.4 Ensure that the --read-only-port argument is set to 0 (Manual)
[PASS] 4.2.5 Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Manual)
[FAIL] 4.2.6 Ensure that the --protect-kernel-defaults argument is set to true (Automated)
[PASS] 4.2.7 Ensure that the --make-iptables-util-chains argument is set to true (Automated)
[WARN] 4.2.8 Ensure that the --hostname-override argument is not set (Manual)
[WARN] 4.2.9 Ensure that the --event-qps argument is set to 0 or a level which ensures appropriate event capture (Manual)
[WARN] 4.2.10 Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate (Manual)
[PASS] 4.2.11 Ensure that the --rotate-certificates argument is not set to false (Manual)
[PASS] 4.2.12 Verify that the RotateKubeletServerCertificate argument is set to true (Manual)
[WARN] 4.2.13 Ensure that the Kubelet only makes use of Strong Cryptographic Ciphers (Manual)
```

**What did you expect to happen:**

[PASS] 4.2.6

**Environment** 

kube-bench: 0.6.3
kubernetes: 1.20.7

**Running processes**

```
root      24664  24629  0 Aug03 ?        00:03:08 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf --hostname-override=myhost
myuser 25455 233965  0 10:52 pts/0    00:00:00 grep --color=auto kube
root      99952  99600  0 Jun03 ?        07:03:52 /home/weave/kube-utils -run-reclaim-daemon -node-name=myhost -peer-name=56:18:1f:7e:b2:a4 -log-level=debug
root     100172      1 12 Jun03 ?        7-16:57:03 /usr/local/bin/kubelet --logtostderr=true --v=2 --node-ip=10.10.10.11 --hostname-override=myhost --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/etc/kubernetes/kubelet-config.yaml --kubeconfig=/etc/kubernetes/kubelet.conf --pod-infra-container-image=pause:3.3 --runtime-cgroups=/systemd/system.slice --feature-gates=EphemeralContainers=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin
```

**Configuration files**

```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
nodeStatusUpdateFrequency: "10s"
failSwapOn: True
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: True
  x509:
    clientCAFile: /etc/kubernetes/ssl/ca.crt
authorization:
  mode: Webhook
staticPodPath: /etc/kubernetes/manifests
cgroupDriver: systemd
containerLogMaxFiles: 5
containerLogMaxSize: 10Mi
maxPods: 110
address: 0.0.0.0
readOnlyPort: 0
healthzPort: 10248
healthzBindAddress: 127.0.0.1
kubeletCgroups: /systemd/system.slice
clusterDomain: cluster.local
protectKernelDefaults: true
rotateCertificates: true
clusterDNS:
- 169.254.25.10
kubeReserved:
  cpu: 100m
  memory: 256Mi
resolvConf: "/etc/resolv.conf"
eventRecordQPS: 5
```

**DaemonSet Configuration**

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-bench-node-ds
  namespace: kube-bench
spec:
  selector:
    matchLabels:
      name: kube-bench-node-ds
  template:
    metadata:
      labels:
        name: kube-bench-node-ds
    spec:
      hostPID: true
      containers:
      - name: kube-bench-node-ds
        image: aquasec/kube-bench:0.6.3
        command: ["kube-bench","run","--targets=node","--nosummary","--noremediations"]
        volumeMounts:
          - name: var-lib-etcd
            mountPath: /var/lib/etcd
            readOnly: true
          - name: var-lib-kubelet
            mountPath: /var/lib/kubelet
            readOnly: true
          - name: var-lib-kube-scheduler
            mountPath: /var/lib/kube-scheduler
            readOnly: true
          - name: var-lib-kube-controller-manager
            mountPath: /var/lib/kube-controller-manager
            readOnly: true
          - name: etc-systemd
            mountPath: /etc/systemd
            readOnly: true
          - name: lib-systemd
            mountPath: /lib/systemd/
            readOnly: true
          - name: srv-kubernetes
            mountPath: /srv/kubernetes/
            readOnly: true
          - name: etc-kubernetes
            mountPath: /etc/kubernetes
            readOnly: true
            # /usr/local/mount-from-host/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version.
            # You can omit this mount if you specify --version as part of the command.
          - name: usr-bin
            mountPath: /usr/local/mount-from-host/bin
            readOnly: true
          - name: etc-cni-netd
            mountPath: /etc/cni/net.d/
            readOnly: true
          - name: opt-cni-bin
            mountPath: /opt/cni/bin/
            readOnly: true
      serviceAccountName: kube-bench-sa
      volumes:
        - name: var-lib-etcd
          hostPath:
            path: "/var/lib/etcd"
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: var-lib-kube-scheduler
          hostPath:
            path: "/var/lib/kube-scheduler"
        - name: var-lib-kube-controller-manager
          hostPath:
            path: "/var/lib/kube-controller-manager"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: lib-systemd
          hostPath:
            path: "/lib/systemd"
        - name: srv-kubernetes
          hostPath:
            path: "/srv/kubernetes"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
        - name: usr-bin
          hostPath:
            path: "/usr/bin"
        - name: etc-cni-netd
          hostPath:
            path: "/etc/cni/net.d/"
        - name: opt-cni-bin
          hostPath:
            path: "/opt/cni/bin/"
```
